services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - api
    tty: true
    ports:
      - "80:80"
      - "443:443"
    shm_size: 256mb
    volumes:
      - ./.logs:/var/log/nginx
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - ./dist/:/dist/:ro
    restart: unless-stopped

  api:
    image: veritas-api:latest
    container_name: api
    ports:
      - "8000:8000"
    shm_size: 256mb
    env_file:
      - .env
    volumes:
      - ./.logs:/var/log/veritas
      - ./.data:/data
      - ./nginx/ssl/:/root/.aspnet/https/:ro
      - ./.temp-keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "1232:80"
      - "5341:5341"
    shm_size: 128mb
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QOHvhYX/JFA3kaXaBBNh8vEzon9ahl7sJGfbt00cXwTCzSdv2NUprUM/yHee7VDZnD3iR0hKtcUfhd6xfJESWF3HZL81moV02gdanBwLlvWZ
    volumes:
      - ./.logs/seq/:/data
    restart: unless-stopped