name: Build and Deploy

on:
  push:
    branches: [ "master" ]

env:
  NETCORE_VERSION: "8.0.x"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Tailwind 🎨
        run: |
          wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss
          chmod +x /usr/local/bin/tailwindcss

      - name: Compile Tailwind classes 🎨
        run: |
          cd ./src/Client
          tailwindcss --input ./wwwroot/css/app.css --output ./wwwroot/css/app.min.css --minify

      - name: Publish 📦
        run: dotnet publish src/Client --configuration Release --output dist

#      - name: Archive up the dist folder 📦
#        run: |
#          tar -cz -v -f dist.tgz /dist/
#          tar -xz -v --overwrite -f dist.tgz -C /dist/

      - name: Copy dist content to server 🔁
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: dist/*
          target: ~/dist
          overwrite: true


#      - publish dist/wwwroot folder.